//movies
export const GET_MOVIES = 'GET_MOVIES';
export const DELETE_MOVIES = 'DELETE_MOVIES';
export const CHANGED_MOVIES_PER_PAGE = 'CHANGED_MOVIES_PER_PAGE';
export const MULTI_SELECT = 'MULTI_SELECT';
export const CHANGED_MOVIES_CURRENTPAGE = 'CHANGED_MOVIES_CURRENTPAGE';
